export const SAVE_CONTENT_TO_SERVER_LOADING = 'SAVE_CONTENT_TO_SERVER_LOADING'
export const SAVE_CONTENT_TO_SERVER_FAILED =  'SAVE_CONTENT_TO_SERVER_FAILED'
export const SAVE_CONTENT_TO_SERVER_SUCCESS = 'SAVE_CONTENT_TO_SERVER_SUCCESS'

export const GET_CONTENT_FROM_SERVER_LOADING = "GET_CONTENT_FROM_SERVER_LOADING"
export const GET_CONTENT_FROM_SERVER_FAILED =  "GET_CONTENT_FROM_SERVER_FAILED"
export const GET_CONTENT_FROM_SERVER_SUCCESS = "GET_CONTENT_FROM_SERVER_SUCCESS"