export const SAVE_CONTENT_TO_SERVER_LOADING = 'SAVE_CONTENT_TO_SERVER_LOADING'
export const SAVE_CONTENT_TO_SERVER_FAILED =  'SAVE_CONTENT_TO_SERVER_FAILED'
export const SAVE_CONTENT_TO_SERVER_SUCCESS = 'SAVE_CONTENT_TO_SERVER_SUCCESS'
