export const GET_SCRIPT_LOADING = 'GET_SCRIPT_LOADING'
export const GET_SCRIPT_FAILED = 'GET_SCRIPT_FAILED'
export const GET_SCRIPT_SUCCESS = 'GET_SCRIPT_SUCCESS'

export const GET_TRANSLATION_LOADING = 'GET_TRANSLATION_LOADING'
export const GET_TRANSLATION_SUCCESS = 'GET_TRANSLATION_SUCCESS'
export const GET_TRANSLATION_FAILED = 'GET_TRANSLATION_FAILED'

export const GET_TAFSIR_LOADING = 'GET_TAFSIR_LOADING'
export const GET_TAFSIR_SUCCESS = 'GET_TAFSIR_SUCCESS'
export const GET_TAFSIR_FAILED = 'GET_TAFSIR_FAILED'