export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_LOADING = 'LOGOUT_LOADING'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const REGISTER_LOADING = 'REGISTER_LOADING'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const GET_SELF_LOADING = "GET_SELF_LOADING"
export const GET_SELF_FAILED = "GET_SELF_FAILED"
export const GET_SELF_SUCCESS = "GET_SELF_SUCCESS"